version: "3.1"

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      SURREAL_URL: ${SURREAL_URL:-http://db:8000/rpc}
      SURREAL_USER: ${SURREAL_USER:-root}
      SURREAL_PASS: ${SURREAL_PASS:-root}
      PROMETHEUS_PORT: ${PROMETHEUS_PORT}
    depends_on:
      - db

  db:
    image: surrealdb/surrealdb:latest
    restart: unless-stopped
    environment:
      USER: ${SURREAL_USER:-root}
      PASS: ${SURREAL_PASS:-root}
      ADDR: 0.0.0.0/0
      DB_PATH: "file:/data"
    volumes:
      - ./db:/data:rw
    command: start
